name: Check Zola links
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: "Run zola check"
        run: |
          mkdir generated
          echo '<svg xmlns="http://www.w3.org/2000/svg">' > ./generated/connections.svg
          docker run -v $(pwd):/site ghcr.io/getzola/zola:v0.16.0 -r site check

