name: Build docker & test site generation
on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Build docker image & Zola
        uses: docker/build-push-action@v4.0.0
      - name: Build the website
        run: docker run -v $(pwd):/build $(docker images --quiet | head -n 1) bash -c "git config --global --add safe.directory /build && cd /build && /website/.venv/bin/ipython umap.ipynb && zola build"
      - name: Zip the website
        run: mkdir docs && zip -r docs/site.zip public
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
