name: Build docker & test site generation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Build docker image & Zola
        uses: docker/build-push-action@v3.1.0

